package calculatorproject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer Laptop
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        allclear1 = new javax.swing.JButton();
        allclear2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        equalsto = new javax.swing.JButton();
        point = new javax.swing.JButton();
        six = new javax.swing.JButton();
        two = new javax.swing.JButton();
        one = new javax.swing.JButton();
        five = new javax.swing.JButton();
        four = new javax.swing.JButton();
        three = new javax.swing.JButton();
        substract = new javax.swing.JButton();
        sum = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        mutiply = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        calculation_area = new javax.swing.JTextArea();
        zero = new javax.swing.JButton();
        allclear = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        allclear1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        allclear1.setText("Ac");
        allclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allclear1ActionPerformed(evt);
            }
        });

        allclear2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        allclear2.setText("Ac");
        allclear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allclear2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        equalsto.setBackground(new java.awt.Color(204, 204, 204));
        equalsto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        equalsto.setForeground(new java.awt.Color(0, 0, 0));
        equalsto.setText("=");
        equalsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalstoActionPerformed(evt);
            }
        });

        point.setBackground(new java.awt.Color(204, 204, 204));
        point.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        point.setForeground(new java.awt.Color(0, 0, 0));
        point.setText(".");
        point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(204, 204, 204));
        six.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        six.setForeground(new java.awt.Color(0, 0, 0));
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(204, 204, 204));
        two.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        two.setForeground(new java.awt.Color(0, 0, 0));
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(204, 204, 204));
        one.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        one.setForeground(new java.awt.Color(0, 0, 0));
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        five.setBackground(new java.awt.Color(204, 204, 204));
        five.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        five.setForeground(new java.awt.Color(0, 0, 0));
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(204, 204, 204));
        four.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        four.setForeground(new java.awt.Color(0, 0, 0));
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(204, 204, 204));
        three.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        three.setForeground(new java.awt.Color(0, 0, 0));
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        substract.setBackground(new java.awt.Color(204, 204, 204));
        substract.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        substract.setForeground(new java.awt.Color(0, 0, 0));
        substract.setText("-");
        substract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractActionPerformed(evt);
            }
        });

        sum.setBackground(new java.awt.Color(204, 204, 204));
        sum.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        sum.setForeground(new java.awt.Color(0, 0, 0));
        sum.setText("+");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        divide.setBackground(new java.awt.Color(204, 204, 204));
        divide.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        divide.setForeground(new java.awt.Color(0, 0, 0));
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        mutiply.setBackground(new java.awt.Color(204, 204, 204));
        mutiply.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mutiply.setForeground(new java.awt.Color(0, 0, 0));
        mutiply.setText("X");
        mutiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mutiplyActionPerformed(evt);
            }
        });

        nine.setBackground(new java.awt.Color(204, 204, 204));
        nine.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nine.setForeground(new java.awt.Color(0, 0, 0));
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        eight.setBackground(new java.awt.Color(204, 204, 204));
        eight.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        eight.setForeground(new java.awt.Color(0, 0, 0));
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(204, 204, 204));
        seven.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        seven.setForeground(new java.awt.Color(0, 0, 0));
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        calculation_area.setBackground(new java.awt.Color(255, 255, 255));
        calculation_area.setColumns(1);
        calculation_area.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        calculation_area.setForeground(new java.awt.Color(0, 0, 0));
        calculation_area.setRows(1);
        jScrollPane1.setViewportView(calculation_area);

        zero.setBackground(new java.awt.Color(204, 204, 204));
        zero.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        zero.setForeground(new java.awt.Color(0, 0, 0));
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        allclear.setBackground(new java.awt.Color(204, 204, 204));
        allclear.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        allclear.setForeground(new java.awt.Color(0, 0, 0));
        allclear.setText("Ac");
        allclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allclearActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(204, 204, 204));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 0, 0));
        clear.setText("<-");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Simple Calculator");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(allclear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(substract, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(mutiply, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)
                                            .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(equalsto, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allclear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mutiply, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(substract, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sum, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalsto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static String recursion(String problem) {
        if (problem == null || problem.isEmpty()) {
            return "0";  // Return 0 for empty input
        }
        
        // If the problem is a number, return it directly
        if (problem.matches("-?\\d+(\\.\\d+)?")) {
            return problem;
        }

        char[] prob = problem.toCharArray();
        String result = null;

        for (int i = prob.length - 1; i >= 0; i--) { // Fixed loop index bounds
            if (prob[i] == '+' || prob[i] == '-' || prob[i] == 'X' || prob[i] == '/') {  // Fixed 'X' to '*'
                char operator = prob[i];

                // Extract operands
                String operand1 = problem.substring(i + 1);
                String operand2 = recursion(problem.substring(0, i));  // Recursively solve left part

                switch (operator) {
                    case '+' -> result = sum(operand1, operand2);
                    case '-' -> result = subtract(operand1, operand2);
                    case 'X' -> result = multiply(operand1, operand2);
                    case '/' -> result = divide(operand1, operand2);
                    default -> System.out.println("Error: Unknown operator");
                }      
                return result;
            }
        }

        return problem; // If no operator found, return the number itself
    }

    // Implement mathematical operations
    public static String sum(String a, String b) {
        return String.valueOf(Double.parseDouble(b) + Double.parseDouble(a));
    }

    public static String subtract(String a, String b) {
        return String.valueOf(Double.parseDouble(b) - Double.parseDouble(a));
    }

    public static String multiply(String a, String b) {
        return String.valueOf(Double.parseDouble(b) * Double.parseDouble(a));
    }

    public static String divide(String a, String b) {
        double divisor = Double.parseDouble(a);
        if (divisor == 0) return "Error: Division by Zero";
        return String.valueOf(Double.parseDouble(b) / divisor);
    }
    
    private void equalstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalstoActionPerformed
        
        String problem = calculation_area.getText();
        String result = recursion(problem);
        calculation_area.setText(result);
        
    }//GEN-LAST:event_equalstoActionPerformed

    private void pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("."));
    }//GEN-LAST:event_pointActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("6"));
    }//GEN-LAST:event_sixActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("2"));
    }//GEN-LAST:event_twoActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("1"));
    }//GEN-LAST:event_oneActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("5"));
    }//GEN-LAST:event_fiveActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("4"));
    }//GEN-LAST:event_fourActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("3"));
    }//GEN-LAST:event_threeActionPerformed

    private void substractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("-"));
    }//GEN-LAST:event_substractActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("+"));
    }//GEN-LAST:event_sumActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("/"));
    }//GEN-LAST:event_divideActionPerformed

    private void mutiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mutiplyActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("X"));
    }//GEN-LAST:event_mutiplyActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("9"));
    }//GEN-LAST:event_nineActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("8"));
    }//GEN-LAST:event_eightActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
         String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("7"));
    }//GEN-LAST:event_sevenActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        String calculation = calculation_area.getText();
        calculation_area.setText(calculation.concat("0"));
    }//GEN-LAST:event_zeroActionPerformed

    private void allclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allclearActionPerformed
        calculation_area.setText("");
    }//GEN-LAST:event_allclearActionPerformed

    private void allclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allclear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allclear1ActionPerformed

    private void allclear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allclear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allclear2ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       String calculation = calculation_area.getText();
       if(calculation.length()>=1)
       {
           calculation_area.setText(calculation.substring(0, calculation.length()-1));
       }
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allclear;
    private javax.swing.JButton allclear1;
    private javax.swing.JButton allclear2;
    private javax.swing.JTextArea calculation_area;
    private javax.swing.JButton clear;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equalsto;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mutiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton point;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton substract;
    private javax.swing.JButton sum;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
